-- Transputer/occam flag simulation -- constants that identify flag types
-- vim: ft=occam
--
-- Forfeited into the public domain with NO WARRANTY. Read LICENSE for details.


-- Constants identifying various flag types; the current DOS frontend supports
-- no more than nine (the number of number keys on the main keyboard)
VAL kFlagTrans IS 0 :
VAL kFlagBotswana IS 1 :
VAL kFlagEstonia IS 2 :
VAL kFlagLuxembourg IS 3 :
VAL kFlagBenin IS 4 :
VAL kFlagMali IS 5 :
VAL kFlagFrance IS 6 :
VAL kFlagPeru IS 7 :
VAL kFlagUk IS 8 :
VAL kFlagChequered IS 9 :
